#!/bin/bash -l


# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "=========================================================="

module load python/2.7.5
module load bowtie2/2.2.9
module load boost/1.58.0
module load tophat/2.1.1
#module load parallel # don't use parallel of the parallelled threads, instead use 'batch' submission to distribute jobs on SCC nodes to better utilze the resources
module load samtools/1.4

INFILE=`find /restricted/projectnb/chengcancer/Simon/project/T2D/bulk_RNA-seq/merge_170415_NB501164_170506_NB501164/0raw/*_R1_001.fastq.gz | sed 's/_R1_001.fastq.gz$//'| head -${SGE_TASK_ID} |tail -1`
echo "NOW in TASK ${SGE_TASK_ID} : PROCESSING $INFILE ..."

# call tophat for individual file distributed by task id
tophat -p $NSLOTS -G /restricted/projectnb/chengcancer/Simon/project/T2D/bulk_RNA-seq/Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf  -o ${INFILE}_thout  /restricted/projectnb/chengcancer/nsun/ReferenceData/GenomeData/Bowtie2/hg38/hg38  ${INFILE}_R1_001.fastq.gz  ${INFILE}_R2_001.fastq.gz

